### PR TITLE
Updated - Resolve `sync` only after heads have been added

### PR DESCRIPTION
**Pull request by msterle**
Builds off of #38, resolving issue with event listeners.

Allows https://github.com/orbitdb/orbit-db/pull/606 to be merged.

### CODE REVIEW

**Comment by oed** [comment]
@chmanie For you to review as well :)

**Comment by chmanie** [comment]
This has been a long time coming :)

LGTM, really! Happy we're getting this in after all

**Comment by aphelionz** [comment]
What say you, @haadcode and @shamb0t ?

**Comment by aphelionz** [comment]
@msterle Thanks for your patience in getting this merged. I'm having some issues running the automated tests against this, but I don't think it's your fault at the moment. It looks like an `js-ipfs` version thing. Would you be willing to help me unravel this? We can meet up on Gitter and walk through it. I just made a commit to `orbit-db-test-utils` that unblocks us partly.

**Comment by aphelionz** [comment]
@msterle LGTM! :+1:

**Pull request merged**
