### PR TITLE
json parse _addOperation data

### PR DESCRIPTION
**Pull request by tabcat**

### CODE REVIEW

**Comment by aphelionz** [comment]
Thanks @tabcat! Would you mind writing up a quick description that includes a couple things? They can be short.

1. The rationale behind the pull request
2. The description of the source file changed
3. An explanation of the new test

**Comment by tabcat** [comment]
@aphelionz sure! My motivation for making this pr is that currently when adding an entry into the store the oplog and cache values for the entries can mismatch if 1) entries are added that session 2) the data has a different value after being JSON.stringify'd then JSON.parse'd. This behavior is easily seen when looking at higher level stores in OrbitDB like a docstore, when you add something next time you open that store you could get something different back. 
The added test checks to make sure that the entry emitted by _addOperation is returning, the entry in the oplog, and the entry stored in the cache all have equal and serialized payloads.
The source file change is simply adding a line that json parses the data before handing it to the oplog:
```js
async _addOperation (data, batchOperation, lastOperation, onProgressCallback) {
    if (this._oplog) {
      // check local cache?
      if (this.options.syncLocal) {
        await this.syncLocal()
      }

      + data = JSON.parse(JSON.stringify(data))

      const entry = await this._oplog.append(data, this.options.referenceCount)
      this._recalculateReplicationStatus(this.replicationStatus.progress + 1, entry.clock.time)
      await this._cache.set(this.localHeadsPath, [entry])
      await this._updateIndex()
      this.events.emit('write', this.address.toString(), entry, this._oplog.heads)
      if (onProgressCallback) onProgressCallback(entry)
      return entry.hash
    }
  }
```
Unfortunately I had an indentation issue which was the cause of the two subsequent commits. 
`Very embarrassed! This usually doesnt happen i swear!` 😋

**Comment by aphelionz** [comment]
Thank you! Don't worry about the indentation. If you can rebase and squash this into one commit that would be helpful, but you can wait until approval for that.

**Comment by aphelionz** [comment]
@shamb0t I think this is OK to merge

**Comment by vaultec81** [comment]
@aphenlionz @tabcat
Just my 2 cents on this issues. (I don't know the full extend of how orbitdb works internally) Using JSON.stringify and JSON.parse, the behavior for serialization is rooted into JavaScript. I think it would make sense to serialize using a universal standard such as JSON-dag or cbor-dag.

**Comment by tabcat** [comment]
thanks for the comment, i hadn't thought of this! need to take another look at how everything is working together for this

**Comment by tabcat** [comment]
if im remembering correctly i believe orbit-db uses json internally for storing data locally but it was not serializing it before handing it to ipfs, and i never could actually find how ipfs was serializing it except that it was eventually dag cbor.

**Comment by aphelionz** [comment]
@vaultec81 I think that's a good thought and in fact we do format our data when it goes into IPFS. Take a look at this repo: https://github.com/orbitdb/orbit-db-io/ to get a sense of the options and what we do for a default (CBOR, CID v1)

**Comment by aphelionz** [comment]
That is to say, this bit should be JS-compatible, so I think it's OK, at least for now :+1:

**Comment by tabcat** [comment]
going to close this as i dont believe its needed all that much anymore

**Pull request closed without merging**
