### PR TITLE
Fix store sync method

### LINKED ISSUE #34: Left-over from ipfs-log refactoring
There's some leftover using the old `write` set as before inside the `sync` function (https://github.com/orbitdb/orbit-db-store/blob/master/src/Store.js#L235), that breaks when an access controller is passed to the store

### PR DESCRIPTION
**Pull request by thiagodelgado111**
## Description

Fix orbit-db-store `sync` method, removing leftovers from the last refactoring

## Other changes

Changed `.then` to use `async/await`

## Notes

We need a function to validate entries to be exposed by the log or maybe use one of the factory methods for that

Closes #34

### CODE REVIEW

**Comment by thiagodelgado111** [comment]
Hey @shamb0t, sure, I'll remove it. But there was a comment saying we should verify entries https://github.com/orbitdb/orbit-db-store/pull/35/files#diff-7a95c660669a260e384552aaa39be4bfL240

**Comment by shamb0t** [comment]
Thanks! Yea, its an old comment but you're right that it should be in ipfs-log

**Comment by thiagodelgado111** [comment]
Hi, @shamb0t! Removed the verification as you asked, shall we merge this one? :) (To master or any other branch)

**Comment by shamb0t** [comment]
Thank you @thiagodelgado111! :heart:

**Pull request merged**
